service: flexi-micro-v1

custom:
  stage: ${opt:stage, self:provider.stage, 'dev'}
  secrets: ${file(settings-${self:custom.stage}.yml)}

provider:
  name: aws
  region: us-east-1
  versionFunctions: false
  runtime: nodejs16.x
  timeout: 120

  iamRoleStatements:
    - Effect: Allow
      Action:
        - DynamoDB:Query
        - DynamoDB:Scan
        - DynamoDB:UpdateItem
        - DynamoDB:GetItem
        - DynamoDB:PutItem
        - DynamoDB:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["teacherstable", "Arn"] }
        - { "Fn::GetAtt": ["studentstable", "Arn"] }

  environment:
    NODE_ENV: ${self:custom.stage}
    TEACHERS_TABLE: teachers-tbl-${self:custom.stage}
    STUDENTS_TABLE: students-tbl-${self:custom.stage}
    USER_POOL_ID: ${self:custom.secrets.USER_POOL_ID}
    CLIENT_ID: ${self:custom.secrets.CLIENT_ID}

package:
  exclude:
    - test/**
    - node_modules/aws-sdk/**

functions:
  login:
    handler: handler.login
    events:
      - http:
          method: POST
          path: /login
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
  addStudent:
    handler: handler.addStudent
    events:
      - http:
          method: POST
          path: /add-student
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
  removeStudent:
    handler: handler.removeStudent
    events:
      - http:
          method: POST
          path: /remove-student
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
  getStudents:
    handler: handler.getStudents
    events:
      - http:
          method: GET
          path: /students
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id

resources:
  Resources:
    teacherstable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "teachers-tbl-${self:custom.stage}"
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 3
    studentstable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "students-tbl-${self:custom.stage}"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 3
